name: 'publish'
on:
  push:
    branches:
      - release

jobs:
  dispatch-to-app-releases:
    name: "Dispatch release workflow to app-releases repo"
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch build_and_release workflow to releases repo
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'StackBaker',
              repo: 'app-releases',
              workflow_id: 'build_and_release.yml',
              ref: 'master'
            })